# Generated by Django 5.0.2 on 2024-02-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_session_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='urls_visited',
        ),
        migrations.AddField(
            model_name='session',
            name='url_visited',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
