# Generated by Django 5.0.2 on 2024-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_short',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
