# Generated by Django 5.0.2 on 2024-03-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_unverifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_editable',
            field=models.BooleanField(default=False),
        ),
    ]
