# Generated by Django 5.0.2 on 2024-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
