# Generated by Django 5.0.2 on 2024-03-11 01:08

import users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email2'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.user.CustomUserAuthManager()),
            ],
        ),
        migrations.RenameField(
            model_name='unverifieduser',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
