# Generated by Django 5.0.2 on 2024-03-08 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_oauthuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
