name: Deploy Django Blog Home to ECR

on:
  push:
    branches: [django-home-docker]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: django-home-docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: portfolio-django-home
          VAULT_ADDR: ${{ secrets.DJANGO_VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.DJANGO_VAULT_TOKEN }}
        run: |
          sed -i 's#{{ .Data.data.VAULT_ADDR }}#'"$VAULT_ADDR"'#g' django/Dockerfile.prod
          sed -i 's#{{ .Data.data.VAULT_TOKEN }}#'"$VAULT_TOKEN"'#g' django/Dockerfile.prod
          export IMAGE_TAG=$(date '+%Y.%m.%d.%N')
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f django/Dockerfile.prod
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
