name: Deploy Django Blog Home to ECR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        # Optionally remove or modify the custom ref if you want to use the tag commit
        # with:
        #   ref: django-home-docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Set IMAGE_TAG and Output
        id: set-image-tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          SHORT_SHA=${GITHUB_SHA::8}
          IMAGE_TAG="${TAG_NAME}-${SHORT_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Current tag name: $TAG_NAME"

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: portfolio-django-home
          VAULT_ADDR: ${{ secrets.DJANGO_VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.DJANGO_VAULT_TOKEN }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          sed -i 's#{{ .Data.data.VAULT_ADDR }}#'"$VAULT_ADDR"'#g' Dockerfile.prod
          sed -i 's#{{ .Data.data.VAULT_TOKEN }}#'"$VAULT_TOKEN"'#g' Dockerfile.prod
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f Dockerfile.prod
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
